Repository Clueless-Community/collegeAPI, pull requests merged in 2022-10, with the labels that each got.

#31 Management Colleges Added with NIRF Ranking And To Fetch Via City And State
  data/allManagementColleges.json
  data/nirfManagementColleges.json
  main.py
  src/filters.py
Labels: hacktoberfest-accepted

#60 Added 4 new engineering colleges
  data/allEngineeringColleges.json
Labels: good first issue, hacktoberfest-accepted

#61 added engineering colleges in siliguri
  data/allEngineeringColleges.json
Labels: good first issue, hacktoberfest-accepted

#77 Update allEngineeringColleges.json
  data/allEngineeringColleges.json
Labels: hacktoberfest-accepted

#84 Function concept is used to tackle line of code in filters.py
  data/allEngineeringColleges.json
  src/filters.py
Labels: hacktoberfest-accepted, done
